version: '3.1'

services:
  db:
    container_name: "user_bot_db"
    image: postgres:14

    restart: always

    ports:
      - "5432:5432"

    environment:
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME
